### ISSUE TITLE
Implement SignalR-Server side

### ISSUE THREAD

**Issue by Mojtabarezaei4** [Mojtabarezaei4/Queueomatic#104]
This includes the support of a unique communication channel for each room.

**Comment by FabianAronsson** [comment]
How do we handle the creation of SignalR hubs? I could not find any information if FE has built in support for this. Does this mean we create these features using the Microsoft supported way? In other words, with minimal api?

**Comment by Mojtabarezaei4** [comment]
I'm not sure yet. I also am looking for some possible solutions.

**Comment by FabianAronsson** [comment]
I have been looking around and unfortunately it seems like you have to use the microsoft way of setting up SignalR and using it.

**Comment by Mojtabarezaei4** [comment]
Me too. We try with Microsoft.
