### ISSUE TITLE
Create custom error page

### ISSUE THREAD

**Issue by FabianAronsson** [Mojtabarezaei4/Queueomatic#110]
This page should show whenever someone is trying to access a page that they do not have the authorization for or if they accidentally try to access a page that does not exist. 

So a 404 page essentially.

It should show that something went wrong. It does not have to be very precise. This would be a nice addition since the base error page is not very visually pleasing.

**Comment by Mojtabarezaei4** [comment]
Very good point! 

Should we make one for every type of status code? Or just one for all?

**Comment by FabianAronsson** [comment]
One for all. If it is possible to know why you reach the page you could make a generic page for any status code.
