### ISSUE TITLE
Deprecation of the enhancement tag

### ISSUE THREAD

**Issue by FabianAronsson** [Mojtabarezaei4/Queueomatic#111]
The current enhancement tag at the moment does not contribute to anything meaningful, and I therefore suggest we remove it to not cause unncessary confusion. 

We already have other tags that more accurately describe what the issue relates to.

If a contributor wants to propose the use of a new tech stack or nuget packages, we should have a tag for that specifically. In all other cases our current tags cover those situations.

The new tags name could be something like: "Suggestion", "Idea", "Proposition".

**Comment by Mojtabarezaei4** [comment]
I agree. 

Do you have any other suggestions about if we should remove any? Besides adding more?

**Comment by FabianAronsson** [comment]
No. Although, perhaps we should decapitalize our current tags?

**Comment by Mojtabarezaei4** [comment]
But don't you agree that we cloud have an enhancement/feature tag for telling that it is a new feature or something similar?

**Comment by FabianAronsson** [comment]
I was under the imperssion that out current tags meant exactly that. UI = feature for the UI, but maybe it is good to keep a separate tag for features?

**Comment by Mojtabarezaei4** [comment]
When I see "Enhancement" "UI", then I read it like it is a new feature for UI. It also can be like "Bug" "UI".

**Comment by Mojtabarezaei4** [comment]
But I think we should have new ones as you suggested.

**Comment by FabianAronsson** [comment]
Which ones? Just a general suggestion tag like the ones I mentioned?

**Comment by Mojtabarezaei4** [comment]
Yeah, we go with "Suggestion". It should be combined with more tags though.
