### ISSUE TITLE
Handle signup scenario where a user already exists

### ISSUE THREAD

**Issue by FabianAronsson** [Mojtabarezaei4/Queueomatic#126]
If you signup with an email you get redirected to the error page without any information as to why. There should be a check on the signup page for this and some information displayed to the user

**Comment by Mojtabarezaei4** [comment]
This is because of we didn't want to inform that which emails are stored in our database, as we discussed.

**Comment by FabianAronsson** [comment]
That is true, but I find the user experience to be very degraded when doing it like that. Surely there is a different way of doing it?
