### ISSUE TITLE
Migrate SignalR methods to interfaces

### ISSUE THREAD

**Issue by Mojtabarezaei4** [Mojtabarezaei4/Queueomatic#142]
Currently all signalR methods rely on string based method invocation. This is not ideal since it is easy to accidentally invoke the wrong method or even no method at all.

This should be changed to an interface based method invocation where each interface corresponds to a method in the backend and if possible in the frontend. Check the link below for an example.

**Comment by FabianAronsson** [comment]
https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-7.0#strongly-typed-hubs
