### ISSUE TITLE
Small bug for showing the room name for owner.

### ISSUE THREAD

**Issue by Mojtabarezaei4** [Mojtabarezaei4/Queueomatic#163]
When an owner joins its room from its profile page, the room name is not passed to the room page.

**Comment by FabianAronsson** [comment]
I verified this in #165 and it seems to work? I am not sure when this changed, but perhaps we just missed to tag it in a PR.

I tried looking for which PR we fixed it, but I can't find it. Can you verify that this works @Mojtabarezaei4?

**Comment by Mojtabarezaei4** [comment]
yeah, I think I fixed a similar issue in #165, I can double-check it.

**Comment by FabianAronsson** [comment]
Closing as this seems to be working.
