### ISSUE TITLE
Make navigation-bar responsive

### ISSUE THREAD

**Issue by FabianAronsson** [Mojtabarezaei4/Queueomatic#174]
Currently the text gets cramped at the medium resolutions which should be changed.

If the container is too small it is okay to change the layout of the buttons as long as the text is always fully visible.

**Comment by Mojtabarezaei4** [comment]
@FabianAronsson  Can you put a pic of this issue?

**Comment by FabianAronsson** [comment]
I have made a mistake. I was on the wrong branch when reviewing #175. It works as intended 💯
