### ISSUE TITLE
Add rate limiter

### ISSUE THREAD

**Issue by FabianAronsson** [Mojtabarezaei4/Queueomatic#21]
In case someone has ill intentions

**Comment by Mojtabarezaei4** [comment]
I assume it's just a deletion of the participants from the room. In that case, we have an endpoint to call for deleting a certain participant.

**Comment by FabianAronsson** [comment]
No no, rate limiting means in case someone is trying to spam the endpoint. This issue is means simply to either add a rate limiting middleware by microsoft or from [FE](https://fast-endpoints.com/docs/rate-limiting#endpoint-rate-limiting).

**Comment by Mojtabarezaei4** [comment]
Oh my bad, I misunderstood the comment 😄

**Comment by Mojtabarezaei4** [comment]
Unnecessary because of no benefits of it for our case.
