### ISSUE TITLE
Api specification

### ISSUE THREAD

**Issue by Mojtabarezaei4** [Mojtabarezaei4/Queueomatic#37]
List of api endpoints

### Example
|            Path             | RequestMethod | RequestParams | QueryParams | RequestBody | ResponseCodes |     ResponseBody     | Authorization  |
| :-------------------------: | :-----------: | :-----------: | :---------: | :---------: | :-----------: | :------------------: | :------------: |
|        api/rooms/{hashIds}         |      GET      |       roomsId       |      -      |      -      |      OK, NotFound       |   RequestedRoom   |      None      |

**Comment by Mojtabarezaei4** [comment]
|                Path                | RequestMethod | RequestParams  | QueryParams | RequestBody | ResponseCodes  |    ResponseBody     |        Authorization         |
| :--------------------------------: | :-----------: | :------------: | :---------: | :---------: | :------------: | :-----------------: | :--------------------------: |
|             api/rooms              |      GET      |       -        |      -      |      -      |       OK       |    List of Room     |       Respective User        |
|        api/rooms/{hashIds}         |      GET      |    Rooms Id    |      -      |      -      |  OK, NotFound  |   Requested Room    |              -               |
|         api/users/{email}          |      GET      |   User Email   |      -      |      -      | OK, BadRequest |   Requested User    |       Respective User        |
|         api/users/{email}          |      PUT      |   User Email   |      -      |    User     | OK, BadRequest |    Updated User     |       Respective User        |
|         api/users/{email}          |    DELETE     |   User Email   |      -      |      -      | OK, BadRequest |          -          |       Respective User        |
| api/rooms/{hashIds}/newParticipant |     POST      |       -        |      -      | Participant | OK, BadRequest |          -          |              -               |
|  api/rooms/{hashIds}/participants  |      GET      |    Rooms Id    |      -      |      -      | OK, BadRequest | List of Participant |              -               |
|       api/participants/{id}        |      PUT      | Participant Id |      -      | Participant | OK, BadRequest | Updated Participant | Respective User & Room Owner |
|       api/participants/{id}        |    DELETE     | Participant Id |      -      | Participant | OK, BadRequest |          -          | Respective User & Room Owner |
|             api/signup             |     POST      |       -        |      -      |    User     | OK, BadRequest |          -          |              -               |
|             api/login              |     POST      |       -        |      -      |    User     | OK, BadRequest |          -          |              -               |


@FabianAronsson your review on this. This will go to the wiki when it's done.

**Comment by FabianAronsson** [comment]
Couple of things at first glance. 

1. Request and response should have types specified.
2. Response codes should be written in numbers format.
3. Authorization should only be specified if the the request *needs* to be authorized, otherwise it should be left out.

**Comment by Mojtabarezaei4** [comment]
|                 Path                 | RequestMethod |  RequestParams  |  RequestBody  | ResponseCodes |        ResponseBody        |        Authorization         |
| :----------------------------------: | :-----------: | :-------------: | :-----------: | :-----------: | :------------------------: | :--------------------------: |
|             `api/rooms`              |      GET      |        -        |       -       |     `200`     |    `IEnumerable<Room>`     |       Respective User        |
|        `api/rooms/{hashIds}`         |      GET      |  ` Id: string`  |       -       |  `200, 404`   |           `Room`           |              -               |
|         `api/users/{email}`          |      GET      | `Email: string` |       -       |  `200, 400`   |           `User`           |       Respective User        |
|         `api/users/{email}`          |      PUT      | `Email: string` |    `User`     |  `200, 400`   |           `User`           |       Respective User        |
|         `api/users/{email}`          |    DELETE     | `Email: string` |       -       |  `200, 400`   |             -              |       Respective User        |
| `api/rooms/{hashIds}/newParticipant` |     POST      |        -        | `Participant` |  `200, 400`   |             -              |              -               |
|  `api/rooms/{hashIds}/participants`  |      GET      | `Id: string   ` |       -       |  `200, 400`   | `IEnumerable<Participant>` |              -               |
|       `api/participants/{id}`        |      PUT      |   `Id: Guid`    | `Participant` |  `200, 400`   |       `Participant`        | Respective User & Room Owner |
|       `api/participants/{id}`        |    DELETE     |   `Id: Guid`    | `Participant` |  `200, 400`   |             -              | Respective User & Room Owner |
|             `api/signup`             |     POST      |        -        |    `User`     |  `200, 400`   |             -              |              -               |
|             `api/login`              |     POST      |        -        |    `User`     |  `200, 400`   |             -              |              -               |


Did I get all?

**Comment by FabianAronsson** [comment]
Shouldn't some of the user endpoints return 401 aswell?

**Comment by FabianAronsson** [comment]
Otherwise it looks good to me!

**Comment by Mojtabarezaei4** [comment]
Yes You are right. But I thought by returning 404 we can hide which user emails are in our db, little security?

**Comment by Mojtabarezaei4** [comment]
I think it will be much better to change some of 200 from post requests to 201, from put and delete to 204 tho.

**Comment by FabianAronsson** [comment]
Sounds good! 👍

**Comment by Mojtabarezaei4** [comment]
|                 Path                 | RequestMethod |  RequestParams  |  RequestBody  | ResponseCodes |        ResponseBody        |        Authorization         |
| :----------------------------------: | :-----------: | :-------------: | :-----------: | :-----------: | :------------------------: | :--------------------------: |
|             `api/rooms`              |      GET      |        -        |       -       |     `200`     |    `IEnumerable<Room>`     |       Respective User        |
|        `api/rooms/{hashIds}`         |      GET      |  ` Id: string`  |       -       |  `200, 404`   |           `Room`           |              -               |
|         `api/users/{email}`          |      GET      | `Email: string` |       -       |  `200, 400`   |           `User`           |       Respective User        |
|         `api/users/{email}`          |      PUT      | `Email: string` |    `User`     |  `204, 400`   |           `User`           |       Respective User        |
|         `api/users/{email}`          |    DELETE     | `Email: string` |       -       |  `204, 400`   |             -              |       Respective User        |
| `api/rooms/{hashIds}/newParticipant` |     POST      |        -        | `Participant` |  `201, 400`   |             -              |              -               |
|  `api/rooms/{hashIds}/participants`  |      GET      | `Id: string   ` |       -       |  `200, 400`   | `IEnumerable<Participant>` |              -               |
|       `api/participants/{id}`        |      PUT      |   `Id: Guid`    | `Participant` |  `204, 400`   |       `Participant`        | Respective User & Room Owner |
|       `api/participants/{id}`        |    DELETE     |   `Id: Guid`    | `Participant` |  `204, 400`   |             -              | Respective User & Room Owner |
|             `api/signup`             |     POST      |        -        |    `User`     |  `201, 400`   |             -              |              -               |
|             `api/login`              |     POST      |        -        |    `User`     |  `200, 400`   |             -              |              -               |
