### ISSUE TITLE
Room validation 

### ISSUE THREAD

**Issue by Mojtabarezaei4** [Mojtabarezaei4/Queueomatic#45]
Each requested room should validate.
Alternative a fluent validation.

**Comment by FabianAronsson** [comment]
What exactly are we validating?

**Comment by Mojtabarezaei4** [comment]
If hashIds that is requesting with does match with any of rooms and also if there is a room with this Id.

**Comment by Mojtabarezaei4** [comment]
This should be done in middleware pipeline.

**Comment by Mojtabarezaei4** [comment]
For that thought, we can implement a mapper that contains that conversion. 

The point of the middleware pipeline will be that it runs before the request hits the handler. Then it will be no need to waste the resources.

**Comment by FabianAronsson** [comment]
How would this mapper work?

**Comment by Mojtabarezaei4** [comment]
A [combination of a validator](https://fast-endpoints.com/docs/validation) with [a mapper](https://fast-endpoints.com/docs/domain-entity-mapping#mapping-logic-in-a-separate-class).

**Comment by FabianAronsson** [comment]
Alright, that looks very interesting!

Let's go with that 👍

**Comment by FabianAronsson** [comment]
Finished in #58
