### ISSUE TITLE
Create all of the endpoint classes, with empty handlers

### ISSUE THREAD

**Issue by Mojtabarezaei4** [Mojtabarezaei4/Queueomatic#46]
This issue focus on registration of the [endpoints](https://github.com/Mojtabarezaei4/Queueomatic/wiki/API-Specification). The handle method does not implement concrete implementation.

**Comment by FabianAronsson** [comment]
Oh, so what you are saying with "registering", is really just creating the empty endpoints? If so, then by all means go for it.

**Comment by Mojtabarezaei4** [comment]
Haha yeah, maybe sounds silly but do get my point of _the issue will get too big_?

**Comment by Mojtabarezaei4** [comment]
For any endpoint, we should make its own issue.

**Comment by FabianAronsson** [comment]
I am not sure if I follow. The way I understood your phrasing was that this issue should create all of the endpoint classes, with empty handlers (which on its own sounds like a lot for one issue). 

FEP automatically scans the program for endpoints and registers them accordingly.
So I am not sure what you mean.
Please clarify.

**Comment by Mojtabarezaei4** [comment]
Sorry for the vague phrasing. But yeah, you understood me right. This issue says ***create all of the endpoint classes, with empty handlers***. 

What do you say we should do for the part you're saying "which on its own sounds like a lot for one issue"?

**Comment by FabianAronsson** [comment]
I am saying that it is a lot to review in one issue. It might just be better to create an issue for each endpoint. That will reduce the scope.

**Comment by Mojtabarezaei4** [comment]
Which includes the implementation of the handlers as well?

**Comment by Mojtabarezaei4** [comment]
Other this to discuss. How should we deal with packing/foldering them? A folder for an endpoint?
```bash
├── server
│   ├── FirstEndpoint
│   │   ├── Request.cs
│   │   ├── Response.cs
│   │   ├── Endpoint.cs
│   │   ├── Mapper.cs
│   │   ├── Validator.cs
│   ├── SecondEndpoint
│   │   ├── Request.cs
│   │   ├── Response.cs
│   │   ├── Endpoint.cs
│   │   ├── Mapper.cs
│   │   ├── Validator.cs
│   ├── Program.cs
```

**Comment by FabianAronsson** [comment]
Leave the handlers empty, but fill the constructors.

That structure looks good! I assume that not all endpoints has validators and mappers right?

**Comment by FabianAronsson** [comment]
> Other this to discuss. How should we deal with packing/foldering them? A folder for an endpoint?
> 
> ```shell
> ├── server
> │   ├── FirstEndpoint
> │   │   ├── Request.cs
> │   │   ├── Response.cs
> │   │   ├── Endpoint.cs
> │   │   ├── Mapper.cs
> │   │   ├── Validator.cs
> │   ├── SecondEndpoint
> │   │   ├── Request.cs
> │   │   ├── Response.cs
> │   │   ├── Endpoint.cs
> │   │   ├── Mapper.cs
> │   │   ├── Validator.cs
> │   ├── Program.cs
> ```

I will add this to the wiki
