### ISSUE TITLE
Add client side api authorization

### ISSUE THREAD

**Issue by FabianAronsson** [Mojtabarezaei4/Queueomatic#82]
This isssue is meant to add support for custom httpclients and similar things

**Comment by Mojtabarezaei4** [comment]
Would you please describe this issue a little more?

**Comment by FabianAronsson** [comment]
At the moment we are using a http client that dosn't requrire you to be logged in to send requests with. This could be changed to one with api authorization.

**Comment by FabianAronsson** [comment]
This might not be necessary though, since we check on the server side if a user can access a resource or not.

**Comment by Mojtabarezaei4** [comment]
So you mean to secure the API by requiring an API authorization? 

It still is a good security to have. We don't want to allow everyone to call our API, not even those open endpoints.

**Comment by Mojtabarezaei4** [comment]
It will be a server-side implementation as well.

**Comment by FabianAronsson** [comment]
Yes, that's what I mean. Maybe it is a good prevention method.

**Comment by Mojtabarezaei4** [comment]
And also best practice, maybe.
