### ISSUE TITLE
Create logout functionality and page

### ISSUE THREAD

**Issue by FabianAronsson** [Mojtabarezaei4/Queueomatic#95]

**Comment by Mojtabarezaei4** [comment]
Is it done on the server side or on the client side?

**Comment by FabianAronsson** [comment]
I was thinking client side. Call the endpoint -> verify the credentials and log in.

**Comment by Mojtabarezaei4** [comment]
Good thinking.

**Comment by Mojtabarezaei4** [comment]
I suggest the logout button should be similar to the "signup" button.
